### ISSUE TITLE
Polling station selection page sometimes hangs on "aan het zoeken..."

### ISSUE THREAD

**Issue by jschuurk-kr** [kiesraad/abacus#191] opened 2024-07-26 13:52 UTC
It's possible to get the polling station page (`/1/input`) to hang on "aan het zoeken..." after you enter a polling station number:
![image](https://github.com/user-attachments/assets/172a9fd7-bdfb-46ee-8f0a-bef5b3fca848)

Might be triggered if the input field is empty, you don't do anything on the page for a while, and then enter a non-existing polling station number.

Initial analysis by Marlon:
- "aan het zoeken..." should render if `loading` or `pollingStationLoading` are `true`
- might be caused by a bug in the `useApiGetRequest` hook or the `useDebounce` hook, causing `load` to be set incorrectly
- possibly unrelated: when you start typing non-numeric characters, an error message is shown immediately, instead of the debounced loader

**Comment by cikzh** [comment] 2024-08-01 13:57
@jschuurk-kr did you manage to reproduce the hanging?

This one is fixed:
>     * possibly unrelated: when you start typing non-numeric characters, an error message is shown immediately, instead of the debounced loader

**Comment by jschuurk-kr** [comment] 2024-08-01 14:22
> @jschuurk-kr did you manage to reproduce the hanging?
> 
> This one is fixed:
> 
> > ```
> > * possibly unrelated: when you start typing non-numeric characters, an error message is shown immediately, instead of the debounced loader
> > ```

@cikzh I thought you'd try to figure it out by walking through the code. Will take some time now to try to reproduce.

**Comment by jschuurk-kr** [comment] 2024-08-01 14:27
@cikzh Did just find something else:
![image](https://github.com/user-attachments/assets/00b53c8d-d51d-4e7a-887b-da39c027337a)

**Comment by cikzh** [comment] 2024-08-01 14:31
In theory the only two ways it can hang in a loading state is when the debounce timer is infinitely reset, which would be caused by a browser event falsely being fired somehow, or when the request to the backend won't respond, but that should eventually resolve in an error state.

**Comment by cikzh** [comment] 2024-08-01 14:36
> @cikzh Did just find something else:

Yes, the `parseInt` problem again. Isn't this a feature? The user accidentally types an extra character, or it pastes in some extra characters from another source, but it finds the polling station nonetheless?

**Comment by jschuurk-kr** [comment] 2024-08-01 14:53
> > @cikzh Did just find something else:
> 
> Yes, the `parseInt` problem again. Isn't this a feature? The user accidentally types an extra character, or it pastes in some extra characters from another source, but it finds the polling station nonetheless?

If it's a feature, then "a33" should work equally well as "33a". And I'm not sure I'd even want that feature, since Abacus should be a rather strict application. (Fuzzy search on polling station number or name would be cool to have, though.)

**Comment by jschuurk-kr** [comment] 2024-08-01 14:55
> @jschuurk-kr did you manage to reproduce the hanging?
> 
> This one is fixed:
> 
> > ```
> > * possibly unrelated: when you start typing non-numeric characters, an error message is shown immediately, instead of the debounced loader
> > ```

I can't reproduce it. When I found it, I got it at least twice without trying too hard.

So am happy to let this one be. If anyone sees it again, they can try to find the steps to reproduce.

**Comment by cikzh** [comment] 2024-08-02 08:07
> If it's a feature, then "a33" should work equally well as "33a". And I'm not sure I'd even want that feature, since Abacus should be a rather strict application. (Fuzzy search on polling station number or name would be cool to have, though.)

We currently use `parseInt` throughout the frontend to convert strings into numbers. We could create a helper function which does a stricter check as we implemented for the URL param validation (with the `$\d+^` RegEx) and replace every `parseInt` call. I think implementation wise that shouldn't be too hard. I'll create a PR.

**Comment by cikzh** [comment] 2024-08-05 11:29
This will be fixed in #193

**Closed** 2024-08-05 14:09 UTC
Labels: frontend
